/* All original website content, used by `npm run db:seed`. */

const EXT = 'https://jupiter-clamps.com/assets/base/img/products';
const GOGTE = 'https://gogtepress.com/wp-content/uploads';

export const settings = {
  site: {
    name: 'Jupiter Industrial Works',
    tagline: 'Since 1963',
    logo: '/images/logo.png',
    logoAlt: 'Jupiter Industrial Works – Since 1963',
    favicon: '/images/logo.png',
    shareImage: '/images/home-factory.jpg',
    titleSuffix: ' | Jupiter Industrial Works',
    metaDescription:
      'Jupiter Industrial Works designs and manufactures high-precision stainless steel clamps, couplings and power press machines for global OEMs since 1963.',
    catalogUrl: '#',
  },
  header: {
    ctaLabel: 'Request a Quote',
    ctaHref: '/contact',
    homeLabel: 'Home',
    aboutLabel: 'About Us',
    powerPressLabel: 'Power Press',
    productsLabel: 'Products',
    pressLabel: 'Insights',
    careersLabel: 'Careers',
    showCareers: true,
    contactLabel: 'Contact',
    extraLinks: [],
    productsMega: {
      eyebrow: 'Products',
      title: 'Clamps Product Range',
      text: 'Precision-engineered clamps for automotive, heavy-duty and industrial assemblies. Standard and fully custom designs.',
      ctaLabel: 'View all products →',
      ctaHref: '/products',
      barText: 'Need a custom or non-standard clamp?',
      barLinkLabel: 'Talk to our engineers →',
      barLinkHref: '/contact',
    },
    powerPressMega: {
      eyebrow: 'Power Press',
      title: 'Power Press Range',
      text: 'Robust C-frame power presses from 5 Ton to 100 Ton, built for accuracy and long-lasting durability.',
      ctaLabel: 'Explore power presses →',
      ctaHref: '/power-press',
      barText: 'Not sure which press fits your job?',
      barLinkLabel: 'Talk to our engineers →',
      barLinkHref: '/contact',
    },
  },
  contact: {
    company: 'Jupiter Industrial Works',
    address: 'ThaneW-347, TTC Industrial Area, MIDC, Rabale, Navi Mumbai – 400701.',
    phone: '+91 89767 37825',
    email: 'marketing@jupiterclamps.com',
    enquiryEmail: 'marketing@jupiterclamps.com',
    hrEmail: 'hr@jupiterclamps.com',
    whatsapp: '+91 89767 37825',
    whatsappLabel: 'Chat with us',
    whatsappMessage: 'Hello Jupiter Industrial Works, I would like to know more about your products.',
  },
  social: { facebook: '#', instagram: '#', linkedin: '#', youtube: '#' },
  footer: {
    about:
      'Since 1959, Jupiter Industrial Works has been designing and manufacturing high-precision Clamps and Power Press Machines. From our pioneering plant in Shrivardhan to advanced units in Rabale and Pune, we bring six decades of engineering reliability and innovation to global OEMs.',
    copyright: '© {year} Jupiter Industrial Works. All rights reserved.',
    ghostText: 'Jupiter Industrial',
    links: [
      { label: 'Home', href: '/' },
      { label: 'About Us', href: '/about' },
      { label: 'Insights', href: '/press' },
      { label: 'Careers', href: '/careers' },
      { label: 'Contact Us', href: '/contact' },
    ],
    productLinks: [
      { label: 'Clamping Solutions', href: '/products' },
      { label: 'Power Press', href: '/power-press' },
    ],
  },
  cta: {
    heading: 'Ready to|Integrate Jupiter',
    em: 'Precision into your assembly lines?',
    ghost: 'Integrate',
    buttons: [
      { label: 'Download Full Catalog', href: '#', style: '' },
      { label: 'Speak to us', href: '/contact', style: 'o' },
    ],
  },
};

export const pages = [
  {
    slug: 'home',
    title: 'Home',
    metaTitle: 'Home',
    isSystem: true,
    sections: [
      {
        type: 'hero_video',
        data: {
          title: 'Precision You Can Rely On.',
          subtitle: 'Innovation Born from Experience.',
          tagline: 'Engineered for industries that demand performance without compromise.',
          text: 'Since 1959, Jupiter Industrial Works has been designing and manufacturing high-precision Clamps and Power Press Machines. From our pioneering plant in Shrivardhan to advanced units in Rabale and Pune, we bring six decades of engineering reliability and innovation to global OEMs.',
          highlights: ['60+ years of hands-on manufacturing expertise', 'Certified IATF 16949:2016 quality systems', '3 manufacturing facilities – Shrivardhan | Rabale | Pune', 'Fully automated production and in-house testing', 'Trusted by OEMs globally, expanding into the European market'],
          video: '/video/hero.mp4',
          poster: '/video/hero-poster.jpg',
          buttons: [
            { label: 'Explore Products', href: '/products', style: '' },
            { label: 'Request a Quote', href: '/contact', style: 'w' },
          ],
        },
      },
      { type: 'marquee', data: { items: ['Jupiter Duplex', '20–100 Ton Press', 'Stainless Steel', 'IATF 16949:2016', 'Custom Designs'], reverse: false } },
      {
        type: 'divisions',
        data: {
          heading: 'Two Divisions.',
          headingAccent: 'One Standard.',
          cards: [
            {
              title: 'Precision Clamps',
              text: 'Engineered for unbeatable grip, leak-proof sealing, and full batch traceability.',
              image: '/images/home-div-clamp.png',
              href: '/products',
              wide: true,
              tags: [
                { label: 'V-Band', href: '/products/v-band-clamps' },
                { label: 'T-Bolt', href: '/products/t-bolt-clamps' },
                { label: 'Worm Drive', href: '/products/worm-drive-clamps' },
                { label: 'Custom Designs', href: '/contact' },
              ],
            },
            {
              title: 'Power Press Machines',
              text: 'Home of the Jupiter Duplex series — revolutionizing efficiency with compact, twin-operation forming. 20–100 Ton variants built for fault-free industrial lifespans.',
              image: '/images/home-div-press.png',
              href: '/power-press',
              wide: false,
              tags: [
                { label: '20 Ton', href: '/power-press' },
                { label: '40 Ton', href: '/power-press' },
                { label: '60 Ton', href: '/power-press' },
                { label: '100 Ton', href: '/power-press' },
              ],
            },
          ],
        },
      },
      {
        type: 'vision',
        data: {
          heading: 'VISION',
          text: 'To design and deliver highest standard of product and service following a systematic approach for utmost customer satisfaction and ensure rewarding growth for our team.',
          image: '/images/home-vision.jpg',
        },
      },
      {
        type: 'mission',
        data: {
          heading: 'MISSION',
          image: '/images/home-mission.jpg',
          items: [
            { icon: 'globe', title: 'Global Custom Solutions', text: 'Delivering tailored industrial joining solutions leveraging deep, cross-sector expertise.' },
            { icon: 'badge', title: 'High-Performance Culture', text: 'Building process-driven, customer-centric teams dedicated to exceeding expectations.' },
            { icon: 'spark', title: 'Tech-Driven Production', text: 'Accelerating international market expansion through advanced automation and new technology.' },
            { icon: 'growth', title: 'Sustained Profitable Growth', text: 'Driving consistent annual profitability through superior service and execution.' },
          ],
        },
      },
      { type: 'marquee', data: { items: ['Quality', 'Innovation', 'Integrity', 'Commitment'], reverse: true } },
      {
        type: 'crafting',
        data: {
          heading: 'Crafting clamping',
          headingAccent: 'solutions since 1962.',
          subheading: "India's most trusted clamping solution partner.",
          stats: [
            { value: 500, suffix: '+', label: 'Working Employees' },
            { value: 100, suffix: '+', label: 'Industrial Products' },
            { value: 500, suffix: 'M', label: 'Products Delivered' },
            { value: 50, suffix: '+', label: 'Years of Mfg. Exp.' },
            { value: 10, suffix: '+', label: 'Countries Served' },
          ],
          ghostA: 'CLAMPING',
          ghostB: 'SOLUTIONS',
          mfSmall: "One of the World's Top Manufacturers of",
          mfTitle: 'Stainless Steel Clamps & Couplings',
          mfText:
            'As a trusted industry expert, Jupiter Industrial Works has been providing high-performance, engineered clamping solutions for over 60+ years. We manufacture precision-crafted stainless steel clamps and heavy-duty industrial couplings designed to withstand the most demanding environments. Our versatile product range delivers fault-free performance across critical global sectors, including:',
          industries: [
            { title: 'Automotive & Heavy-Duty Trucks', text: 'High-vibration fastening and heavy-duty truck clamps engineered for rugged fleet endurance.', image: '/images/home-ind-1.jpg' },
            { title: 'Industrial & Engineering', text: 'Advanced couplings and pipe clips for machinery, fluid handling, and filtration setups.', image: '/images/home-ind-2.jpg' },
            { title: 'Agriculture & Infrastructure', text: 'Heavy-duty irrigation systems, farm equipment, and construction machinery.', image: '/images/home-ind-3.jpg' },
            { title: 'Specialized Sectors', text: 'Turnkey solutions for Renewable Energy, Oil & Gas, Off-Road Vehicles, and Food & Beverage processing lines.', image: '/images/home-ind-4.jpg' },
          ],
        },
      },
      {
        type: 'built_to_scale',
        data: {
          heading: 'Built to Scale',
          headingAccent: 'Traceable to the Source.',
          slides: [
            { ghost: 'SOURCE', title: '3 Advanced Facilities', text: 'Strategically located across Kagal, Shrivardhan, Rabale, and Pune.', image: '/images/home-hero-press.jpg', contain: true },
            { ghost: 'SOURCE', title: 'IATF 16949:2016 Certified', text: 'Stringent quality systems with full reverse batch tracking.', image: '/images/iatf.png', contain: true },
            { ghost: 'SOURCE', title: 'In-House Testing', text: 'Comprehensive Design Validation Process (DVP & R) to ensure flawless performance.', image: '/images/home-factory.jpg', contain: false },
          ],
        },
      },
    ],
  },
  {
    slug: 'about',
    title: 'About Us',
    bodyClass: 'about-page',
    isSystem: true,
    showCta: false,
    sections: [
      {
        type: 'about_hero',
        data: {
          title: 'Built on Craft. Backed by Generations. Driven by Quality.',
          subtitle: 'Pioneer in joining and forming technology since 1963.',
          text:
            'Founded in 1963 by Mr. P.G. Gogate in Shriwardhan, Maharashtra, Jupiter Industrial Works began with a singular focus: delivering uncompromised, fail-proof joining solutions. What started as a visionary workshop has grown over six decades into a multi-facility engineering stalwart serving top-tier global OEMs.\n\nToday, helmed by three generations of engineering expertise, we combine time-honored manufacturing traditions with modern production technology. From developing specialized clamps for US Military standards and gas turbine applications to patenting our proprietary Duplex Power Press series, our legacy is defined by continuous innovation, integrity, and precision engineering.',
          buttonLabel: 'Read Our Full Founding Story',
          buttonHref: '/press/our-founding-story',
          image: '/images/hero.jpg',
        },
      },
      {
        type: 'expertise',
        data: {
          heading: 'Integrated In-House Expertise',
          subheading: 'Complete end-to-end control over design, validation, and surface processing.',
          rows: [
            {
              title: 'Advanced Metallurgy & Special Processes',
              text: 'Equipped with state-of-the-art in-house Trivalent Plating and Heat Treatment facilities. Integrated ETP (Effluent Treatment Plant) units ensure sustainable wastewater recycling across operations.',
              image: '/images/expertise-1.jpg',
            },
            {
              title: 'Design Validation & Reverse Traceability',
              text: 'We operate a rigorous Design Validation Process (DVP & R) backed by custom testing equipment to measure radial strength, torque, and fatigue limits. Every product is embossed with a unique batch number for complete reverse batch tracking.',
              image: '/images/expertise-2.jpg',
            },
            {
              title: 'Specialized Engineering & Patents',
              text: 'Proven track record of developing custom, high-spec designs including patented Constant Pressure Worm Drive Clamps and military-grade clamping systems.',
              image: '/images/expertise-3.jpg',
            },
          ],
        },
      },
      {
        type: 'journey',
        data: {
          heading: 'Decades of Precision: Our Journey',
          background: '/images/timeline-bg.jpg',
          items: [
            { tab: '1963', title: '1963', text: 'Founded by Mr. P.G. Gogate at Shriwardhan, Maharashtra.', image: '/images/timeline-thumb.jpg' },
            { tab: '1967', title: '1967', text: 'Commenced OEM supplies to Kirloskar Cummins Ltd. (now Cummins India Ltd.).', image: '/images/timeline-thumb.jpg' },
            { tab: '1972–1986', title: '1972-1986', text: 'Expanded operations with a dedicated high-tech facility in Thane; restructured into a partnership under Mr. Mahendra P. Gogate.', image: '/images/timeline-thumb.jpg' },
            { tab: '1992', title: '1992', text: 'Secured key patents for the revolutionary Duplex Power Press machine series.', image: '/images/timeline-thumb.jpg' },
            { tab: '1997–2011', title: '1997-2011', text: 'Tapped international markets, establishing direct export channels to Cummins USA plants.', image: '/images/timeline-thumb.jpg' },
            { tab: '2006', title: '2006', text: 'Granted a patent for the Constant Pressure Worm Drive Clamp design.', image: '/images/timeline-thumb.jpg' },
            { tab: '2014–2017', title: '2014-2017', text: 'Acquired and transitioned into an expansive, state-of-the-art owned plant in Rabale.', image: '/images/timeline-thumb.jpg' },
            { tab: '2018–Present', title: '2018-Present', text: 'Upgraded to IATF 16949:2016 certification and implementing modern tools like Lean Manufacturing, Kaizen, Poka-Yoke, and MRP II for scalable global growth.', image: '/images/timeline-thumb.jpg' },
          ],
        },
      },
      {
        type: 'certifications',
        data: {
          heading: 'Certified Quality for Global Benchmarks',
          subheading: 'Quality Badges & Frameworks Display',
          cards: [
            { title: 'IATF 16949:2016 Certified', text: "Meeting the world's most stringent automotive quality management standards.", image: '/images/iatf.png', badge: true },
            { title: 'Modern Operational Tools', text: 'Driven by Kaizen, Lean Manufacturing, MRP II, and Poka-Yoke methodologies.', image: '/images/cert-tools.jpg', badge: false },
            { title: 'Global Footprint', text: 'Delivering engineered solutions to the USA, Europe, and commercial markets worldwide across Automotive, Marine, Agriculture, Filtration, and Energy sectors.', image: '/images/cert-global.jpg', badge: false },
          ],
        },
      },
      {
        type: 'industries_list',
        data: {
          ghost: 'Industries',
          heading: 'Versatile Solutions for Demanding Environments.',
          text: 'We serve industries where the smallest detail makes the biggest difference.',
          items: ['Automotive & Heavy Vehicles', 'Marine & Offshore', 'Agriculture', 'Construction', 'Chemical & Pharmaceutical Systems', 'Irrigation', 'Electrical & Filtration'],
          footer: 'Each product is performance-proven and tested in real-world conditions to match demanding global standards.',
        },
      },
      {
        type: 'cta_banner',
        data: {
          heading: 'Looking for custom clamping|or press solutions',
          em: 'tailored to your operational specifications?',
          ghost: 'Custom',
          buttons: [
            { label: 'Explore Product Catalog', href: '/products', style: '' },
            { label: 'Contact Our Engineering Team', href: '/contact', style: 'o' },
          ],
        },
      },
    ],
  },
  {
    slug: 'products',
    title: 'Clamps Product Range',
    isSystem: true,
    sections: [{ type: 'product_grid', data: { title: 'Clamps Product Range', ghost: 'Products', text: 'Two divisions. One standard – designed to perform. Clamps engineered for unbeatable grip, performance, and traceability.', linkLabel: 'Explore range →' } }],
  },
  {
    slug: 'power-press',
    title: 'Power Press Range',
    isSystem: true,
    sections: [
      { type: 'machine_feature', data: { machineId: null } },
      { type: 'machines_grid', data: { title: 'Power Press Range', ghost: 'Power Press', text: 'The Jupiter Duplex Power Press revolutionized pressing efficiency with twin operation and compact design. Our range includes single crank machines and Duplex Power Press machines in 20–100 Ton variants for high-load precision forming. Every press is developed under stringent quality control and proven across decades of fault-free operation.', linkLabel: 'View machine →' } },
    ],
  },
  {
    slug: 'press',
    title: 'Press',
    isSystem: true,
    sections: [{ type: 'press_list', data: { title: 'Insights', limit: 0, kicker: 'Insights', headline: 'Sharing what six decades have taught us.', text: 'Manufacturing is evolving and so are we. Our insights explore the future of forming and fastening, sustainability in production, and design trends from India to Europe.' } }],
  },
  {
    slug: 'contact',
    title: 'Contact Us',
    isSystem: true,
    sections: [
      {
        type: 'contact_locations',
        data: {
          title: 'Contact Us',
          lead: 'Reach the manufacturing unit closest to you — each of our three plants handles enquiries for T-Bolt clamps and power presses.',
          directionsLabel: 'Get Directions →',
        },
      },
      {
        type: 'contact_form',
        data: {
          heading: "Let's create reliable solutions together",
          text: "Whether you're an OEM, distributor or engineering consultant, we'll help you find the right product or design one for you.",
          bullets: ['Share clamp type, size range and quantity', 'Custom and non-standard clamps on request', 'We respond within one working day'],
          units: ['General enquiry', 'Rabale unit', 'Pune unit', 'Shrivardhan unit'],
          buttonLabel: 'Submit Enquiry',
          successMessage: 'Thank you — your enquiry has been received. Our team will get back to you within one working day.',
        },
      },
    ],
  },
];

export const careersPage = {
  slug: 'careers',
  title: 'Careers',
  metaTitle: 'Careers',
  metaDescription: 'Join Jupiter Industrial Works — current openings at our Rabale, Pune and Shrivardhan units, or send us your CV.',
  isSystem: true,
  sections: [
    { type: 'page_title', data: { title: 'Careers', ghost: 'Join us' } },
    {
      type: 'job_openings',
      data: {
        kicker: 'Join our big family',
        heading: 'Current Openings',
        text: 'We are always looking for engineers, machinists and sales professionals who care about precision. Apply to an opening below, or send us your CV and we will keep it handy.',
        emptyText: 'There are no open positions right now. Send us your CV below and we will contact you when a suitable role opens.',
        applyLabel: 'Apply Now',
        successMessage: 'Thank you — your application has been sent to our HR team. We will get back to you shortly.',
      },
    },
    {
      type: 'cv_form',
      data: {
        heading: 'Send us your CV & we will keep it handy',
        text: 'Join our team and contribute to the process of creating engineering wonders!',
        bullets: ['Attach your CV as PDF or Word (max 5 MB)', 'Tell us the role or department you are interested in', 'Our HR team replies within one working week'],
        buttonLabel: 'Submit',
        successMessage: 'Thank you — your CV has been received. Our HR team will be in touch.',
        phone: '+91 89767 37825',
        whatsapp: '918976737825',
        email: 'hr@jupiterclamps.com',
      },
    },
  ],
};

export const jobs = [
  {
    title: 'Quality Engineer – IATF 16949',
    department: 'Quality',
    location: 'Rabale, Navi Mumbai',
    type: 'Full-time',
    experience: '3 - 6 yrs',
    positions: 1,
    qualifications: 'B.E. / Diploma in Mechanical or Production Engineering. Hands-on experience with IATF 16949 systems, PPAP, APQP and reverse batch traceability in an automotive component plant.',
    description: '<p>You will own incoming, in-process and final inspection for our clamp lines, run DVP &amp; R testing (radial strength, torque, fatigue) and drive corrective actions with production.</p><ul><li>Maintain IATF 16949 documentation and customer PPAP files</li><li>Operate and calibrate torque, salt-spray and fatigue test rigs</li><li>Lead 8D / CAPA with suppliers and shop floor</li></ul>',
    order: 0,
  },
  {
    title: 'Press Shop Operator – Power Press',
    department: 'Production',
    location: 'Pune (Hinjewadi)',
    type: 'Full-time',
    experience: '2 - 5 yrs',
    positions: 4,
    qualifications: 'ITI / Diploma (Fitter, Tool & Die or Mechanical). Experience operating 10 – 100 Ton C-frame power presses, die setting and basic maintenance. Shift work.',
    description: '<p>Operate and set up single and duplex power presses for blanking, forming and piercing of clamp bands and segments.</p><ul><li>Die loading, shut-height and stroke adjustment</li><li>First-piece approval and in-process checks</li><li>Daily lubrication and safety checks</li></ul>',
    order: 1,
  },
  {
    title: 'Sales Engineer – OEM Accounts',
    department: 'Sales',
    location: 'Mumbai / travel across India',
    type: 'Full-time',
    experience: '5 - 10 yrs',
    positions: 2,
    qualifications: 'Diploma or Graduation in Engineering. Minimum 5 years selling engineered components (clamps, fasteners, hoses) to automotive and heavy-duty OEMs. Must have good communication skills in English.',
    description: '<p>Grow our OEM and Tier-1 accounts for V-band, T-bolt and worm-drive clamps across western and southern India.</p><ul><li>Technical discussions with design and purchase teams</li><li>Quotations, samples and PPAP coordination with the plant</li><li>Quarterly forecasts and receivables follow-up</li></ul>',
    order: 2,
  },
  {
    title: 'Design Engineer – Clamping Solutions',
    department: 'Engineering',
    location: 'Rabale, Navi Mumbai',
    type: 'Full-time',
    experience: '2 - 4 yrs',
    positions: 1,
    qualifications: 'B.E. Mechanical with SolidWorks / AutoCAD. Experience in sheet-metal part design, tolerance stack-up and DFM for stamping and welding.',
    description: '<p>Design custom and non-standard clamps from customer drawings, create 3D models and manufacturing drawings, and support prototype trials.</p>',
    order: 3,
  },
].map((j) => ({ ...j, published: true }));

const clampIndustries = [
  { label: 'Automobiles', image: '/images/ind-1.jpg' },
  { label: 'Heavy Trucks', image: '/images/ind-2.jpg' },
  { label: 'Duct Connections', image: '/images/ind-3.jpg' },
  { label: 'RABH Filteration', image: '/images/ind-4.jpg' },
];
const clampMaterials = ['AISI 201', 'AISI 304', 'AISI 316 L', 'IS 513-CR1', 'SAE 1541', 'AISI 410', 'IS 4454-GR III', 'SAE 1010'];
const clampFeatureTags = ['Flexibility', 'Wider Band widths', 'Vibration proof', 'Corrosion-resistant', 'Strength', 'Light-weight', 'Clamping of metallic inserts', 'Mutifarious design aspect', 'Reliability'];

export const productCategories = [
  {
    slug: 'v-band-clamps',
    name: 'V-Band Clamps',
    order: 0,
    layout: 'hero',
    cardText: 'Couplings to join piping, tubing, turbo chargers, engine joints and gas or liquid tracks.',
    cardImage: `${EXT}/vband/images/v-band-clamp-with-center-opening-and-3v-segments.png`,
    kicker: 'Overview',
    title: 'V-Band Clamps',
    subtitle: 'How a V-Band Coupling Clamp Works',
    description:
      'V-band clamps provide a secure, leak-proof seal for high-pressure pipe and flange connections. Instead of relying on multiple heavy bolts, a single V-band clamp applies equal pressure all the way around the joint.',
    chips: ['Leak-proof seal', 'Uniform 360° pressure', 'Vibration-resistant'],
    heroImage: `${EXT}/vband/images/v-band-clamp-with-center-opening-and-3v-segments.png`,
    badgeBig: '360°',
    badgeText: 'equal pressure|around the joint',
    ctaPrimaryLabel: 'Request a Quote',
    ctaPrimaryHref: '/contact',
    ctaSecondaryLabel: 'Download Catalog',
    ctaSecondaryHref: '#',
    featuresKicker: 'What sets it apart',
    featuresHeading: 'Key Features & Customization',
    features: [
      { icon: 'sliders', title: 'Tailored Designs', text: 'Built to specific application requirements, featuring quick-release latches, toggle latches, or standard T-bolts.' },
      { icon: 'sun', title: 'Custom Construction', text: 'Clamp shape, bolt size, segment count, band thickness, and materials are customized for your operating environment.' },
      { icon: 'layers', title: 'Complete Assembly', text: 'Consists of a T-bolt, locking nut, trunnion, and an outer band welded to internal V-shaped retainer segments.' },
    ],
    stepsKicker: 'Step by step',
    stepsHeading: 'How the Mechanical Seal Works',
    steps: [
      { title: 'Mounting', text: 'The inner V-segments sit directly over the tapered edges of two mating pipe flanges.' },
      { title: 'Tightening', text: 'As the T-bolt nut is tightened, it pulls the outer band taut around the joint.' },
      { title: 'Radial Pressure', text: 'This tightening creates a uniform inward radial force across the entire 360° circumference.' },
      { title: 'Wedging Action', text: 'The angled V-segments press against the flange tapers, generating a wedging force.' },
      { title: 'Axial Lock', text: 'This wedging action converts into a strong axial force that draws the two flange faces tightly together for a vibration-resistant seal.' },
    ],
    designsKicker: 'Our range',
    designsHeading: 'V-Band Clamp Designs',
    products: [
      ['V-band Clamp with Centre Opening & 3 V-segments', 'v-band-clamp-with-center-opening-and-3v-segments.png'],
      ['V-band Clamp with Nut side Opening & 3 V-segments', 'v-band-clamp-with-nut-side-opening-and-3-v-segments.png'],
      ['V-band Clamp with 2 V-segments', 'v-band-clamps-with-2v-segments.png'],
      ['V-band Clamp with twin T-Bolt & 4 V-segments', 'v-band-clamp-with-twin-t-bolt-and-4v-segments.png'],
      ['V-band Clamp with twin T-Bolt & 2 V-segments', 'v-band-clamp-with-twin-t-bolt-and-2v-segments.png'],
      ['V-band Clamp with endlink & without band - 2 V-segments', 'v-band-clamp-with-endlink-and-without-band-2v-segments.png'],
      ['Worm Drive V-band Clamp with 3 V-segments', 'worm-drive-v-band-clamp-with-3v-segments.png'],
      ['Worm Drive V-band Clamp with Riveted Housing & 3 V-segments', 'worm-drive-v-band-clamp-with-reveted-housing-and-3v-segents.png'],
      ['V-band Clamp without band & 1 V-segment', 'v-band-clamp-without-band-and-1v-segments.png'],
      ['V-band Clamp without Band & 2 V-segments', 'v-band-clamp-without-band-and-2v-segment.png'],
      ['V-band Clamp with Quick Opening Toggle Latch & 4 V-segments', 'v-band-clamp-withquick-opening-toggle-latch-and-4v-segments.png'],
      ['V-band Clamp with Quick Opening Latch & 3 V-segments', 'v-band-clamp-withquick-opening-toggle-latch-and-3v-segments.png'],
      ['V-band Clamp with Quick Opening Latch, Knob & 3 V-segments', 'v-band-clamp-withquick-opening-toggle-latch-knob-and-3v-segments.png'],
    ].map(([name, file], i) => ({ name, image: `${EXT}/vband/images/${file}`, order: i })),
  },
  {
    slug: 'worm-drive-clamps',
    name: 'Worm-Drive Clamps',
    order: 1,
    layout: 'hero',
    cardText: 'Smooth, corrosion-resistant solutions for everyday hose applications.',
    cardImage: `${EXT}/worm/images/worm_drive_clamp_with_12_mm_wide_band.png`,
    kicker: 'Overview',
    title: 'Worm-Drive Clamps',
    subtitle: 'Strong, reliable sealing for standard hose connections',
    description:
      'Worm-drive clamps provide a strong, reliable seal for standard hose connections, preventing slack and leakage under high torque. Turning the captive screw engages the threaded band, drawing it tight and applying even pressure around the hose.',
    chips: ['Low tightening torque', 'Self-locking nyloc nut', 'Stainless steel'],
    heroImage: `${EXT}/worm/images/worm_drive_clamp_with_12_mm_wide_band.png`,
    badgeBig: '360°',
    badgeText: 'even pressure|around the hose',
    ctaPrimaryLabel: 'Request a Quote',
    ctaPrimaryHref: '/contact',
    ctaSecondaryLabel: 'Download Catalog',
    ctaSecondaryHref: '#',
    featuresKicker: 'Key benefits',
    featuresHeading: 'Key Benefits & Features',
    features: [
      { icon: 'bolt', title: 'High Performance', text: 'Delivers superior clamping pressure with low tightening torque, featuring high safe-torque values to eliminate dangerous slippage and coolant leaks.' },
      { icon: 'shield', title: 'Vibration & Climate Proof', text: 'Uses self-locking nyloc nuts or springs to prevent loosening under vibration, and maintains a leak-proof seal from high temperatures to below 0°C.' },
      { icon: 'layers', title: 'Hose-Friendly Design', text: 'The solid strip-type band distributes pressure evenly across wider surface areas without biting into soft silicon or rubber hoses like wire/holed clamps do.' },
      { icon: 'sliders', title: 'Versatile & Durable', text: 'Stainless steel construction offers maximum corrosion resistance, high band flexibility, and wide clamping ranges to reduce inventory needs.' },
      { icon: 'drop', title: 'Eco-Friendly', text: 'Designed with minimal or omitted zinc plating to comply with environmental protection standards.' },
    ],
    products: [
      { name: 'Worm Drive Clamp with 12 mm wide band', image: `${EXT}/worm/images/worm_drive_clamp_with_12_mm_wide_band.png`, order: 0 },
      { name: 'Tension Spring Clamp with spiral band', image: `${EXT}/worm/images/tension_spring_clamp_with_spiral_band.png`, order: 1 },
    ],
  },
  {
    slug: 'spring-band-clamps',
    name: 'Spring Band Clamps',
    order: 2,
    layout: 'hero',
    cardText: 'Self-tightening, tool-free clamps that hold a constant seal through temperature and pressure changes.',
    cardImage: `${EXT}/worm/images/tension_spring_clamp_with_spiral_band.png`,
    kicker: 'Overview',
    title: 'Spring Band Clamps',
    subtitle: 'Self-tightening, tool-free fasteners',
    description:
      'Spring band clamps are self-tightening, tool-free fasteners engineered for automatic adjustment under changing temperatures and pressures. Built from high-grade spring steel, they continuously apply dynamic tension to maintain a constant, leak-proof seal over time.',
    chips: ['Self-adjusting tension', 'Tool-free assembly', '-40°C to +200°C'],
    heroImage: `${EXT}/worm/images/tension_spring_clamp_with_spiral_band.png`,
    badgeBig: '200°C',
    badgeText: 'rated from|-40°C',
    ctaPrimaryLabel: 'Request a Quote',
    ctaPrimaryHref: '/contact',
    ctaSecondaryLabel: 'Download Catalog',
    ctaSecondaryHref: '#',
    featuresKicker: 'Key benefits',
    featuresHeading: 'Key Benefits & Features',
    features: [
      { icon: 'spark', title: 'Self-Adjusting Tension', text: 'Dynamic spring action automatically compensates for thermal expansion, pressure shifts, and hose aging.' },
      { icon: 'sun', title: 'Extreme Temperature Range', text: 'Operates reliably in harsh environments from -40°C up to +200°C.' },
      { icon: 'shield', title: 'Vibration-Proof & Lightweight', text: 'Low-mass construction ensures secure connection on vibrating components without risk of loosening.' },
      { icon: 'layers', title: 'Hose Protection', text: 'Solid band profile delivers uniform radial pressure across a wide contact area, preventing damage to sensitive silicone or rubber hoses.' },
      { icon: 'wrench', title: 'Reusable & Maintenance-Free', text: 'Ideal for systems requiring frequent mounting and dismounting without losing clamping performance.' },
    ],
    featureTags: ['Complies with SAE J1508', 'DIN 3021 Type A', 'Eco-friendly zinc-flake coating', 'One-piece sheet-metal construction'],
    applications: [
      { title: 'Automotive', text: 'Fuel lines, air/water pipes, steering systems, coolant loops, and engine construction.' },
      { title: 'Industrial & HVAC', text: 'Heat pumps, commercial AC units, compressors, and LPG installations.' },
      { title: 'Specialized Machinery', text: 'Agricultural, construction, printing, floor-cleaning equipment, and commercial dishwashers.' },
    ],
    products: [{ name: 'Tension Spring Clamp with spiral band', image: `${EXT}/worm/images/tension_spring_clamp_with_spiral_band.png`, order: 0 }],
  },
  {
    slug: 'strap-bands',
    name: 'Strap Bands',
    order: 3,
    layout: 'hero',
    cardText: 'Heavy-duty strap band clamps to mount and secure tanks, cylindrical bodies and large pipes.',
    cardImage: '/images/strap-band.jpg',
    kicker: 'Overview',
    title: 'Strap Band Clamps',
    subtitle: 'Superior holding power for tanks, cylinders and large pipes',
    description:
      'Jupiter Strap Band Clamps are engineered for heavy-duty, high-performance applications, providing superior holding power to mount and secure cylindrical bodies, tanks, and large pipes. Designed for both industrial and automotive environments, they deliver exceptional grip under severe operational loads.',
    chips: ['High-load security', 'Corrosion resistant', 'Vibration resistant'],
    heroImage: '/images/strap-band.jpg',
    badgeBig: 'JR',
    badgeText: 'type codes|material · design · width',
    ctaPrimaryLabel: 'Request a Quote',
    ctaPrimaryHref: '/contact',
    ctaSecondaryLabel: 'Download Catalog',
    ctaSecondaryHref: '#',
    featuresKicker: 'Customization & benefits',
    featuresHeading: 'Build Options & Key Benefits',
    features: [
      { icon: 'sliders', title: 'Tailored Dimensions', text: 'Sized to match specific tank, pipe, and vehicle mounting specifications.' },
      { icon: 'layers', title: 'Versatile Materials', text: 'Available in AISI 304, AISI 441, AISI 439, Mild Steel (MS), or custom alloy requests.' },
      { icon: 'target', title: 'Smart Part Coding', text: 'Decoded via standard type codes covering Material, Design, and Bandwidth (e.g., Models JR 40 22, JR 7N 40, JR 7N 50, JR 70 32, JR 4A 62, JR 7U 25).' },
      { icon: 'shield', title: 'High-Load Security', text: 'Engineered specifically to retain heavy industrial tanks and components without slippage.' },
      { icon: 'drop', title: 'Corrosion Resistance', text: 'High-grade stainless steel options ensure longevity against environmental exposure and road chemicals.' },
      { icon: 'bolt', title: 'Vibration Resistant', text: 'Maintains structural stability and firm clamping force in high-vibration automotive and heavy equipment applications.' },
    ],
    materials: ['AISI 304', 'AISI 441', 'AISI 439', 'Mild Steel (MS)', 'Custom alloys on request'],
    applications: [
      { title: 'Automotive & Commercial Vehicles', text: 'Fuel tanks, Urea tanks, and EATS (Exhaust Aftertreatment System) tanks.' },
      { title: 'Industrial & Electrical', text: 'Battery mounting brackets, air filter housing, and large process piping.' },
    ],
    products: [
      { name: 'Standard Strap Band', description: 'Plain stainless steel strap bands in a range of widths and thicknesses.', image: '/images/strap-band.jpg', order: 0 },
      { name: 'Custom Mounting Band', description: 'Bands with brackets, slots and welded studs made to customer drawings.', image: '/images/strap-band.jpg', order: 1 },
    ],
  },
  {
    slug: 'pipe-fitting-clips',
    name: 'Pipe Fitting Clips',
    order: 4,
    layout: 'hero',
    cardText: 'Heavy-duty clips for quick, secure mounting of piping, tubing and electrical conduits.',
    cardImage: `${EXT}/pipe/images/pipe-clip-with-sleeve.png`,
    kicker: 'Overview',
    title: 'Pipe Fitting Clips',
    subtitle: 'Heavy-duty support and mounting for pipes, tubes and conduits',
    description:
      'Jupiter Pipe Fitting Clamps are engineered for heavy-duty support and mounting, offering a quick, secure way to clamp piping, tubing, and electrical conduits to structural surfaces. Supplied in an open position for fast installation, they wrap around the pipe and are tightened via screw fixings with optional reinforced washers.',
    chips: ['Over 20 design types', 'Protective sleeve options', '172–400 h salt-spray tested'],
    heroImage: `${EXT}/pipe/images/pipe-clip-with-sleeve.png`,
    badgeBig: '20+',
    badgeText: 'design types|JP 01 – JP 719',
    ctaPrimaryLabel: 'Request a Quote',
    ctaPrimaryHref: '/contact',
    ctaSecondaryLabel: 'Download Catalog',
    ctaSecondaryHref: '#',
    featuresKicker: 'Customization & benefits',
    featuresHeading: 'Build Options & Key Benefits',
    features: [
      { icon: 'layers', title: 'Versatile Material Choices', text: 'Available in Mild Steel (M.S.), AISI 202 Stainless Steel, AISI 304 Stainless Steel, and AISI 316 Stainless Steel.' },
      { icon: 'sliders', title: 'Wide Range of Designs', text: 'Offers over 20 distinct design types (Types JP 01 through JP 21, JP 22, JP 23, and JP 719) to match specific mounting profiles.' },
      { icon: 'shield', title: 'Protective Sleeve Options', text: 'Available with Heat Shrinkable PVC, Neoprene Rubber, Nitrile Rubber, EPDM Rubber, or Vinyl Plastisol Coating.' },
      { icon: 'target', title: 'Smart Part Coding', text: 'Decoded via standard type codes covering Material, Design Type, and Sleeve Construction (e.g., Pipe vs. Channel, coated vs. uncoated).' },
      { icon: 'bolt', title: 'Fast & Simple Assembly', text: 'Delivered in an open state so technicians can fit them directly over existing piping runs without disassembling lines.' },
      { icon: 'wrench', title: 'High Torque & Load Capacity', text: 'Optional spot-welded washer reinforcement at the screw mounting point provides superior clamping strength.' },
      { icon: 'drop', title: 'Long-Lasting Corrosion Resistance', text: 'Electroplated with eco-friendly trivalent chemicals, enduring 172 to 400 hours of salt-spray testing.' },
      { icon: 'shieldCheck', title: 'Surface Protection', text: 'Protective rubber and plastisol sleeves shield delicate pipes from edge wear and vibration friction, extending overall system life.' },
    ],
    materials: ['Mild Steel (M.S.)', 'AISI 202', 'AISI 304', 'AISI 316'],
    products: [
      { name: 'Pipe Clip with Sleeve', description: 'Rubber or plastisol-sleeved clip isolates vibration and protects pipe finishes.', image: `${EXT}/pipe/images/pipe-clip-with-sleeve.png`, order: 0 },
      { name: 'Pipe Clip without Sleeve', description: 'Plain metal clip for rigid tube and conduit routing.', image: `${EXT}/pipe/images/pipe-clip-with-sleeve.png`, order: 1 },
    ],
  },
  {
    slug: 't-bolt-clamps',
    name: 'T-Bolt Clamps',
    order: 5,
    layout: 'hero',
    cardText: 'Heavy-duty fastening with exceptional durability for hoses, split tubes and engine connections.',
    cardImage: `${EXT}/tbolt/images/t-bolt-clamp-tb-type.png`,
    kicker: 'Overview',
    title: 'T-Bolt Clamps',
    subtitle: 'Heavy-duty, high-strength fastening under pressure and vibration',
    description:
      'Jupiter T-Bolt Clamps are heavy-duty, high-strength fasteners designed to secure hoses, split tubes, and heavy engine connections under high pressure and vibration. Built with a hardened stainless-steel band and a heat-treated, zinc-plated or stainless-steel T-bolt, they deliver leak-proof clamping for heavy industrial and automotive machinery.',
    chips: ['SAE J1508 compliant', 'Band widths 16 – 31.75 mm', 'AISI 301 / 304 / 316'],
    heroImage: `${EXT}/tbolt/images/t-bolt-clamp-tb-type.png`,
    badgeBig: '31.75',
    badgeText: 'mm max|band width',
    ctaPrimaryLabel: 'Request a Quote',
    ctaPrimaryHref: '/contact',
    ctaSecondaryLabel: 'Download Catalog',
    ctaSecondaryHref: '#',
    featuresKicker: 'Key benefits',
    featuresHeading: 'Key Benefits & Features',
    features: [
      { icon: 'layers', title: 'Superior Radial Pressure', text: 'Wider band widths distribute clamping force evenly across the hose surface compared to narrow or wire clamps.' },
      { icon: 'shield', title: 'Vibration-Proof Locking', text: 'Fitted with self-locking nyloc nuts or spring elements to eliminate loosening during dynamic engine operation.' },
      { icon: 'bolt', title: 'High Tensile & Lightweight', text: 'Delivers extreme tensile holding strength without adding unnecessary weight to the assembly.' },
      { icon: 'drop', title: 'Corrosion & Re-use Resistant', text: 'High-grade stainless steel construction ensures long service life, corrosion resistance, and safe reusability.' },
      { icon: 'sliders', title: 'Flexible Fitting', text: 'Automatically adjusts to minor variations in circular mating diameters better than rigid, thick-walled mild steel clamps.' },
    ],
    featureTags: ['Built to SAE J 1508', 'Full stainless or hybrid (AISI 301, 304, 316)', 'Part code J - [Design] - [Material] - [Band Width]', 'Band widths 16 mm to 31.75 mm'],
    materials: ['AISI 301', 'AISI 304', 'AISI 316', 'Hybrid stainless / zinc-plated T-bolt'],
    applications: [
      { title: 'Heavy Engines', text: 'Intake, coolant, and exhaust connections on heavy-duty commercial vehicles and engines.' },
      { title: 'Air Cleaners & Metallic Inserts', text: 'Securing split tubular sheet iron over metallic intake tubes.' },
      { title: 'Custom Assemblies', text: 'Tailored options for quick-opening latches, constant torque systems, and custom O.D. sizes.' },
    ],
    industriesHeading: 'Industries & Application',
    industries: clampIndustries,
    products: [
      { name: 'T-Bolt Clamp - TB Type -Standard clamp', description: 'The flat shoe of bridge clamp is widely used for general application.', image: '/images/clamp-card.jpg', order: 0 },
      { name: 'T-Bolt Clamp with Special floating bridge', description: 'This is generally used for soft surface like silicon hose connection and special applications.', image: '/images/clamp-card.jpg', order: 1 },
      { name: 'Spring loaded T-Bolt Clamps (SLTB Type)', description: 'This spring loaded clamp is used for safety of assembly of hose or connected components from excessive pressure than the necessary.', image: '/images/clamp-card.jpg', order: 2 },
      { name: 'Twin T-Bolt Clamp (Wide range Clamp)', description: 'This is double T-bolt clamp designed for higher range of clamping requirement.', image: '/images/clamp-card.jpg', order: 3 },
      { name: 'Quick Opening T-Bolt Clamp', description: 'This construction helps to avoid complete opening of nut and facilities easy mounting or dismounting.', image: '/images/clamp-card.jpg', order: 4 },
      { name: 'Torque Limiter Clamp', description: 'This construction helps to avoid breakage of plastic or fibre component', image: '/images/clamp-card.jpg', order: 5 },
      { name: 'Special Non-Standard clamps', description: 'Non-Standard clamps with various widths, Thickness, T-Bolt, Nut specifications and special finishing, mountings are designated to suit the customer requirements.', image: '/images/clamp-card.jpg', order: 6 },
    ],
  },
  {
    slug: 'muffler-clamps',
    name: 'Muffler Clamps',
    order: 6,
    layout: 'grid',
    cardText: 'Robust exhaust and muffler clamps for tight, leak-free automotive joints.',
    cardImage: '/images/muffler-clamp.jpg',
    title: 'Muffler Clamps',
    designsHeading: 'Muffler Clamps',
    materialsHeading: 'Material Opts',
    materials: clampMaterials,
    industriesHeading: 'Industries & Application',
    industries: clampIndustries,
    products: [
      { name: 'U-Bolt Muffler Clamp', description: 'Classic saddle and U-bolt design for exhaust pipe joints.', image: '/images/muffler-clamp.jpg', order: 0 },
      { name: 'Band Muffler Clamp', description: 'Wide-band clamp for a 360° leak-free exhaust seal.', image: '/images/muffler-clamp.jpg', order: 1 },
    ],
  },
  {
    slug: 'customised-clamps',
    name: 'Customised Clamps',
    order: 7,
    layout: 'hero',
    cardText: 'Precision clamps built to your exact specifications, from drawings to production.',
    cardImage: '/images/clamp-card.jpg',
    kicker: 'Custom engineering',
    title: 'Customised Clamps',
    subtitle: 'Have a unique clamping requirement?',
    description:
      "At Jupiter, we recognize that standard off-the-shelf clamps don't always fit specialized machinery, extreme operating environments, or unique spatial constraints. Backed by end-to-end design and manufacturing capabilities, we offer complete customization services to build clamps tailored to your exact specifications. Our engineering team works directly with you from initial design and drawings to final production.",
    chips: ['Design to production', 'Material & coating selection', 'Single-piece or modular'],
    heroImage: '/images/clamp-card.jpg',
    badgeBig: '1:1',
    badgeText: 'built to your|specifications',
    ctaPrimaryLabel: 'Get in Touch with Our Engineering Team',
    ctaPrimaryHref: '/contact',
    featuresKicker: 'Why customise',
    featuresHeading: 'Key Benefits of Jupiter Customization',
    features: [
      { icon: 'target', title: 'Precision Fit', text: 'Eliminates slippage, stress concentration, and leak risks in specialized automotive, industrial, and heavy machinery applications.' },
      { icon: 'clock', title: 'Extended Application Life', text: 'Material and coating combinations selected specifically for your operating medium, temperature range, and environmental exposure.' },
      { icon: 'growth', title: 'Cost Efficiency', text: 'Streamlined single-piece or modular designs reduce assembly labor and eliminate the need for expensive structural modifications.' },
    ],
    products: [],
  },
];

const pressFeatures = [
  { icon: 'wrench', title: 'Low Maintenance', text: 'Built for smooth running with minimal upkeep, keeping downtime low.' },
  { icon: 'shield', title: 'Hardened and Grounded components', text: 'Flywheel, crank shaft and other parts are duly hardened and ground for long-lasting durability.' },
  { icon: 'bolt', title: 'Power Saving', text: 'A properly sized, balanced flywheel stores and releases energy as needed during pressing.' },
  { icon: 'drop', title: 'Continuous Lubrication System', text: 'Keeps moving parts lubricated at all times for smooth, accurate operation.' },
  { icon: 'layers2', title: 'High Durability', text: 'Steel-plate frame with cross ribbings and a special alloy steel crank shaft.' },
  { icon: 'shieldCheck', title: 'Unique Safety Features', text: 'Designed with operator safety in mind, without compromising productivity.' },
];

const specColumns = ['5 Ton', '10 Ton', '20 Ton', '30 Ton', '50 Ton', '75 Ton', '100 Ton'];
const specRows = [
  ['HP Of Motor (3 Ph. 440V 1440 RPM)', '--', 'H.P/RPM', '0.75 / 1440|1 / 1440|1.5 / 1440|3 / 1440|5 / 1440|7.5 / 1440|10 / 1440'],
  ['Height (Bolster To Floor)', 'A', 'mm', '605|715|715|785|860|900|1020'],
  ['Floor Space (Front To Back)', 'B', 'mm', '400|575|800|850|1000|1350|1650'],
  ['Floor Space (Left To Right)', 'C', 'mm', '350|422|670|702|820|800|800'],
  ['Total Machine Height', 'D', 'mm', '1700|1800|2100|2250|2600|3000|3300'],
  ['Machine Weight (Kg)', '--', 'Kg', '350|480|1100|1400|2400|3500|4600'],
  ['Bolster Sizes (Length x Width x Thickness)', 'E x F x G', 'mm', '290 x 170 x 40|300 x 230 x 48|400 x 310 x 55|510 x 355 x 65|640 x 450 x 65|800 x 500 x 70|900 x 600 x 70'],
  ['Hole Dia In Bed', '--', 'mm', '75|85|100|110|130|140|150'],
  ['Hole Dia In Ram', '--', 'mm', '25|25|32|38|45|45|50'],
  ['Distance Bet. Bolster & Ram Guide', '--', 'mm', '210|252|325|340|390|450|520'],
  ['Shut Height', 'H', 'mm', '135|170|220|230|250|270|300'],
  ['Stroke Adjustment', '--', 'mm', '3 - 26|5 - 48|6 - 54|8 - 70|5 - 80|5 - 100|10 - 120'],
  ['Slide Adjustment By Screw', '--', 'mm', '30|25|50|50|55|60|65'],
  ['Stroke Per Min.', '--', 'S.P.M', '75|70|50|45|40|40|40'],
  ['Machining Prod. Per Min.', '--', 'S.P.M', '75|70|50|45|40|40|40'],
].map(([label, code, unit, values]) => ({ label, code, unit, values }));

export const machines = [
  {
    slug: 'single-power-press',
    name: 'Single Power Press',
    order: 0,
    cardText: '5 – 100 Ton C-frame press',
    kicker: 'Power Press',
    description:
      'Our unique series of Single Power Press machines are tailored to customer-specific requirements that ensures highly credible desired end-product. Duly hardened and grounded, the parts such as flywheel, crank shafts, etc ensures long-lasting durability of the machine. Properly sized flywheel is madeup of high grade CI and is balanced for storing and releasing of energy as desired during pressing. Machined to close accuracy, hardened and ground, then fixed in gun metal bushes for perfect alignment, the crank shaft is made up of special alloy steel. Proper alignment of the press ensured by machining of the profile cut steel plates prior to welding, the frame which is made-up of all steel construction fabricated from steel plates with suitable cross ribbings.',
    image: '/images/press-machine.jpg',
    badgeBig: '5–100',
    badgeText: 'Ton capacity|range',
    ctaPrimaryLabel: 'Contact Us',
    ctaPrimaryHref: '/contact',
    ctaSecondaryLabel: 'View Specifications',
    ctaSecondaryHref: '#specs',
    galleryHeading: 'Machine Gallery',
    gallery: [
      { label: 'Single Power Press', image: `${GOGTE}/2024/02/singl2-768x1024.webp`, href: `${GOGTE}/2024/02/singl2-768x1024.webp` },
      { label: 'Side View', image: `${GOGTE}/2024/02/singl-2-768x1024.webp`, href: '' },
      { label: 'Technical Drawing', image: `${GOGTE}/2024/01/SINGLE-POWER-PRESS-TF-955x1024.jpg`, href: `${GOGTE}/2024/01/SINGLE-POWER-PRESS-TF-955x1024.jpg` },
    ],
    featuresKicker: 'Built to last',
    featuresHeading: 'Features',
    features: pressFeatures,
    specsHeading: 'Technical Specifications',
    specColumns,
    specRows,
  },
  {
    slug: 'duplex-power-press',
    name: 'Duplex Power Press',
    order: 1,
    cardText: 'Compact twin-operation forming',
    kicker: 'Power Press',
    description:
      'The Jupiter Duplex Power Press revolutionized pressing efficiency with twin operation and compact design — two forming operations in a single machine, reducing floor space and handling between stations. Available in 20–100 Ton variants for high-load precision forming, every press is developed under stringent quality control and proven across decades of fault-free operation.',
    image: '/images/press-machine.jpg',
    badgeBig: '2×',
    badgeText: 'operations in|one machine',
    ctaPrimaryLabel: 'Contact Us',
    ctaPrimaryHref: '/contact',
    ctaSecondaryLabel: 'View Specifications',
    ctaSecondaryHref: '#specs',
    galleryHeading: 'Machine Gallery',
    gallery: [{ label: 'Duplex Power Press', image: '/images/press-machine.jpg', href: '' }],
    featuresKicker: 'Built to last',
    featuresHeading: 'Features',
    features: pressFeatures,
    specsHeading: 'Technical Specifications',
    specColumns: ['20 Ton', '30 Ton', '50 Ton', '75 Ton', '100 Ton'],
    specRows: specRows.map((r) => ({ ...r, values: r.values.split('|').slice(2).join('|') })),
  },
  {
    slug: 'gearless-power-press',
    name: 'Gearless Power Press',
    order: 2,
    cardText: 'Gearless drive press range',
    kicker: 'Power Press',
    description:
      'Gearless power presses drive the crank directly from the flywheel for higher strokes per minute, quieter running and fewer wearing parts — ideal for high-volume blanking and piercing of thin sheet.',
    image: '/images/press-machine.jpg',
    badgeBig: '5–30',
    badgeText: 'Ton capacity|range',
    ctaPrimaryLabel: 'Contact Us',
    ctaPrimaryHref: '/contact',
    ctaSecondaryLabel: 'View Specifications',
    ctaSecondaryHref: '#specs',
    galleryHeading: 'Machine Gallery',
    gallery: [{ label: 'Gearless Power Press', image: '/images/press-machine.jpg', href: '' }],
    featuresKicker: 'Built to last',
    featuresHeading: 'Features',
    features: pressFeatures,
    specsHeading: 'Technical Specifications',
    specColumns: ['5 Ton', '10 Ton', '20 Ton', '30 Ton'],
    specRows: specRows.map((r) => ({ ...r, values: r.values.split('|').slice(0, 4).join('|') })),
  },
  {
    slug: 'hydraulic-power-press',
    name: 'Hydraulic Power Press',
    order: 3,
    cardText: 'Hydraulic press range',
    kicker: 'Power Press',
    description:
      'Hydraulic power presses deliver full tonnage anywhere in the stroke with adjustable speed and pressure, suited to deep drawing, coining and assembly operations where control matters more than speed.',
    image: '/images/press-machine.jpg',
    badgeBig: '10–100',
    badgeText: 'Ton capacity|range',
    ctaPrimaryLabel: 'Contact Us',
    ctaPrimaryHref: '/contact',
    galleryHeading: 'Machine Gallery',
    gallery: [{ label: 'Hydraulic Power Press', image: '/images/press-machine.jpg', href: '' }],
    featuresKicker: 'Built to last',
    featuresHeading: 'Features',
    features: pressFeatures,
    specsHeading: 'Technical Specifications',
    specColumns: [],
    specRows: [],
  },
];

const award = `<p>Receiving the Super 8 Participant Award at the Regional Supplier Samrat-FY25 from Ashok Leyland is a significant honor that reflects the collaborative spirit and dedication of our entire team. This prestigious recognition highlights excellence in quality, innovation, and performance within the competitive landscape of the commercial vehicle sector in India.</p>
<p>Being selected for this award among numerous participants underscores our commitment to not only meet but exceed the high standards set by Ashok Leyland. Our journey to this achievement involved a rigorous evaluation process and a focus on continuous improvement initiatives.</p>
<p>We implemented stringent quality control measures to ensure that our clamps meet Ashok Leyland's high expectations. Additionally, we developed new processes and technologies that enhance efficiency and reduce costs, thereby adding substantial value to our partnership. The installation of semi-automated machines has significantly boosted the productivity and reliability of our clamps.</p>
<p>Winning the Super 8 Participant Award is not merely an endpoint; it serves as motivation for us to strive for even greater heights. We are dedicated to further enhancing our capabilities and positively contributing to Ashok Leyland's growth ambitions. Moving forward, we will continue to focus on building stronger ties with Ashok Leyland and other stakeholders in the supply chain.</p>
<p>In conclusion, being honored with the Super 8 Participant Award at the Regional Supplier Samrat-FY25 is a testament to our hard work, dedication, and strategic alignment with Ashok Leyland's vision. We look forward to continuing this journey of excellence together.</p>`;

function body(excerpt) {
  return `<p>${excerpt}</p><p>Jupiter Industrial Works continues to invest in people, processes and technology across its Shrivardhan, Rabale and Pune units. For more information about this update, our product range or partnership opportunities, please contact our marketing team.</p>`;
}

export const posts = [
  {
    slug: 'our-founding-story',
    title: 'Our Founding Story: Built on Craft, Backed by Generations',
    category: 'Company',
    publishedAt: '2026-04-21',
    author: 'Jupiter Industrial Works',
    image: '/images/hero.jpg',
    excerpt: 'Jupiter Industrial Works began as a family-run workshop in 1959. What started in a coastal town grew into one of India’s most respected names in joining and forming technology.',
    body: `<p>Jupiter Industrial Works began as a family-run workshop in 1959. What started in a coastal town grew into one of India’s most respected names in joining and forming technology. Today, we’re helmed by the third generation of innovators who continue our founder’s belief that quality is not an act; it’s a promise.</p>
<p>Our journey blends traditions with technology. Whether developing patented clamp designs or the Duplex Power Press series, our aim is to create solutions that deliver consistently over decades of use.</p>
<h3>At a glance</h3>
<ul>
<li>3 fully equipped manufacturing facilities</li>
<li>In-house Design Validation Process (DVP &amp; R) for quality testing</li>
<li>Advanced Trivalent Plating, Heat Treatment, and ETP units for sustainability</li>
<li>Certified, traceable manufacturing with reverse batch tracking</li>
<li>Supplying to Automotive, Marine, Chemical, and Heavy Engineering sectors</li>
</ul>
<h3>Milestones</h3>
<ul>
<li><b>1963</b> – Founded by Mr. P.G. Gogate at Shriwardhan, Maharashtra.</li>
<li><b>1967</b> – Commenced OEM supplies to Kirloskar Cummins Ltd. (now Cummins India Ltd.).</li>
<li><b>1972–1986</b> – Expanded operations with a dedicated high-tech facility in Thane; restructured into a partnership under Mr. Mahendra P. Gogate.</li>
<li><b>1992</b> – Secured key patents for the revolutionary Duplex Power Press machine series.</li>
<li><b>1997–2011</b> – Tapped international markets, establishing direct export channels to Cummins USA plants.</li>
<li><b>2006</b> – Granted a patent for the Constant Pressure Worm Drive Clamp design.</li>
<li><b>2014–2017</b> – Acquired and transitioned into an expansive, state-of-the-art owned plant in Rabale.</li>
<li><b>2018–Present</b> – Upgraded to IATF 16949:2016 certification and implementing Lean Manufacturing, Kaizen, Poka-Yoke, and MRP II for scalable global growth.</li>
</ul>`,
    views: 0,
    published: true,
  },
  { slug: 'rethinking-clamp-design-for-efficiency', title: 'Rethinking Clamp Design for Efficiency', category: 'Insights', publishedAt: '2026-10-02', author: 'Jupiter Industrial Works', image: '/images/expertise-2.jpg', excerpt: 'Draft — how modern clamp geometry, materials and coatings reduce assembly time and lifetime cost.', body: '<p>Draft article. Edit this text in Press / Insights.</p>', views: 0, published: false },
  { slug: 'duplex-press-technology-compact-power-big-results', title: 'Duplex Press Technology: Compact Power, Big Results', category: 'Insights', publishedAt: '2026-10-02', author: 'Jupiter Industrial Works', image: '/images/press-machine.jpg', excerpt: 'Draft — why twin-operation forming in one compact press changes the economics of a press shop.', body: '<p>Draft article. Edit this text in Press / Insights.</p>', views: 0, published: false },
  { slug: 'building-global-standards-in-local-factories', title: 'Building Global Standards in Local Factories', category: 'Insights', publishedAt: '2026-10-02', author: 'Jupiter Industrial Works', image: '/images/home-factory.jpg', excerpt: 'Draft — bringing IATF 16949, Kaizen and Poka-Yoke to plants in Shrivardhan, Rabale and Pune.', body: '<p>Draft article. Edit this text in Press / Insights.</p>', views: 0, published: false },
  {
    slug: 'jupiter-showcases-power-press-and-clamp-range-at-industrial-trade-show',
    title: 'Jupiter Showcases Power Press and Clamp Range at Industrial Trade Show',
    category: 'Events',
    publishedAt: '2026-09-10',
    author: 'Jupiter Industrial Works Rabale',
    image: '/images/news-team.jpg',
    excerpt: 'Our Rabale team welcomed OEM buyers and channel partners at the Gogte Power Press stall, presenting the latest T-Bolt clamps and the new range of power presses.',
    views: 312,
  },
  {
    slug: 'super-8-participant-award-ashok-leyland-supplier-samrat-fy25',
    title: 'Jupiter Industrial Works Wins Super 8 Participant Award at Ashok Leyland Supplier Samrat FY25',
    category: 'Awards & Recognition',
    publishedAt: '2024-11-22',
    author: 'Jupiter Industrial Works Thane',
    image: '/images/home-factory.jpg',
    excerpt: "Recognition at Ashok Leyland's Regional Supplier Samrat event highlights our commitment to quality, innovation and on-time delivery for commercial vehicles.",
    body: award,
    views: 454,
  },
  {
    slug: 'iatf-16949-certification-reinforces-automotive-quality-standards',
    title: 'IATF 16949 Certification Reinforces Our Automotive Quality Standards',
    category: 'Quality',
    publishedAt: '2026-07-18',
    author: 'Jupiter Industrial Works',
    image: '/images/cert-global.jpg',
    excerpt: 'Our clamp manufacturing units continue to operate under IATF 16949 systems, ensuring traceability and consistency for global OEM customers.',
    views: 198,
  },
  {
    slug: 'new-semi-automated-lines-boost-t-bolt-clamp-output-at-pune-unit',
    title: 'New Semi-Automated Lines Boost T-Bolt Clamp Output at Pune Unit',
    category: 'Manufacturing',
    publishedAt: '2026-06-02',
    author: 'Jupiter Industrial Works Pune',
    image: '/images/expertise-1.jpg',
    excerpt: 'Investment in semi-automated assembly has improved productivity and repeatability across our heavy-duty T-Bolt and Twin T-Bolt clamp ranges.',
    views: 260,
  },
  {
    slug: 'jupiter-expands-single-power-press-range-from-5-ton-to-100-ton',
    title: 'Jupiter Expands Single Power Press Range from 5 Ton to 100 Ton',
    category: 'Products',
    publishedAt: '2026-04-14',
    author: 'Jupiter Industrial Works',
    image: '/images/expertise-2.jpg',
    excerpt: 'Hardened and ground components, continuous lubrication and power-saving drives define our refreshed range of C-frame power presses.',
    views: 221,
  },
  {
    slug: 'six-decades-of-engineering-reliability-since-1963',
    title: 'Six Decades of Engineering Reliability: Jupiter Industrial Works Since 1963',
    category: 'Company',
    publishedAt: '2026-02-05',
    author: 'Jupiter Industrial Works',
    image: '/images/expertise-3.jpg',
    excerpt: 'From our pioneering plant in Shrivardhan to advanced units in Rabale and Pune, we continue to serve global OEMs with precision-engineered clamps.',
    views: 390,
  },
  {
    slug: 'custom-non-standard-clamps-faster-development-cycles',
    title: 'Custom Non-Standard Clamps Now Supported with Faster Development Cycles',
    category: 'Products',
    publishedAt: '2025-12-20',
    author: 'Jupiter Industrial Works',
    image: '/images/home-hero-press.jpg',
    excerpt: 'Special widths, thicknesses and finishes are now developed in shorter lead times to match customer assembly requirements.',
    views: 175,
  },
].map((p) => ({ ...p, body: p.body || body(p.excerpt), published: p.published ?? true }));

export const locations = [
  {
    name: 'Manufacturing unit Rabale',
    tag: 'Rabale',
    address: 'W-347, TTC Industrial Area, MIDC, Rabale, Navi Mumbai 400701.',
    phone: '+91 88991 17923',
    email: 'info@jupiterclamps.com',
    mapQuery: 'W-347, TTC Industrial Area, MIDC, Rabale, Navi Mumbai 400701',
    order: 0,
  },
  {
    name: 'Manufacturing unit Pune',
    tag: 'Pune',
    address: 'S. No. 246/6, Phase 2, Behind Swaraj Bharat Petrol Pump, Beside KTA Tooling Company, Hinjewadi, Pune 411057.',
    phone: '+91 88991 17923',
    email: 'info@jupiterclamps.com',
    mapQuery: 'Behind Swaraj Bharat Petrol Pump, Hinjewadi Phase 2, Pune 411057',
    order: 1,
  },
  {
    name: 'Manufacturing unit Shrivardhan',
    tag: 'Shrivardhan',
    address: 'Dr Ambedkar Road, Shrivardhan, Maharashtra 402110.',
    phone: '+91 88991 17923',
    email: 'info@jupiterclamps.com',
    mapQuery: 'Dr Ambedkar Road, Shrivardhan, Maharashtra 402110',
    order: 2,
  },
];
